machine: 
  node:
    version: 
      v0.10.33
  hosts: 
    main-srv: 188.166.44.244

dependencies:
  pre:
    - npm install -g jasmine-node
    - npm install -g pm2 
    - echo "create database playlist; grant all privileges on playlist.* to 'playlistadmin'@'%'" | mysql -u root 
    - npm run db 
    - pm2 start --name=playlist app.js  
    
test: 
  override: 
    - jasmine-node --verbose --color --growl --forceexit --captureExceptions ./test/* 